export const REQUEST_SUGGESTED_PENDING = "REQUEST_SUGGESTED_PENDING";

export const REQUEST_SUGGESTED_SUCCESS = "REQUEST_SUGGESTED_SUCCESS";

export const REQUEST_SUGGESTED_FAILURE = "REQUEST_SUGGESTED_FAILURE";
