export const REQUEST_STARRED_PENDING = "REQUEST_STARRED_PENDING";

export const REQUEST_STARRED_SUCCESS = "REQUEST_STARRED_SUCCESS";

export const REQUEST_STARRED_FAILURE = "REQUEST_STARRED_FAILURE";

export const REMOVE_STARRED_BY_ID = "REQUEST_STARRED_BY_ID";

export const ADD_INFLUENCER_TO_STARRED = "ADD_INFLUENCER_TO_STARRED";
